

name: golangci-lint
on: [ push, pull_request ]
jobs:
  golangci:
    if: "!contains(github.event.head_commit.message, 'autoupdate')"
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
